# Generated by Django 6.1.1 on 2026-09-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('game_name', models.CharField(max_length=150)),
                ('game_type', models.CharField(max_length=100)),
                ('age_rest', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'Game',
                'ordering': ['game_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('u_age', models.IntegerField()),
                ('pincode', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('passwords', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User',
                'ordering': ['user_id'],
            },
        ),
    ]
